import { type NextPage } from "next";
import Head from "next/head";

import { useAuthState } from "react-firebase-hooks/auth";
import In from "../components/admin/in";
import Out from "../components/admin/Out";

import { auth } from "../lib/firebase";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  const [user] = useAuthState(auth);

  console.log(user);

  return (
    <>
      <Head>
        <title>Huiswerk</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex min-h-screen w-full flex-col items-center justify-center">
          <h1 className="text-center text-7xl font-bold">Huiswerk</h1>

          {user ? <In /> : <Out />}
        </div>
      </main>
    </>
  );
};

export default Home;
